[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = ['cd crypto-intelligence', 'python -m pip install -r requirements.txt']

[start]
cmd = 'cd crypto-intelligence && python -m gunicorn app:app --host 0.0.0.0 --port $PORT'
